spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
            '[/**]':
              allowedOrigins: "*"
              allowedHeaders:
                - "Origin"
                - "Content-Type"
                - "Accept"
                - "Authorization"
                - "Referer"
              allowedMethods:
                - POST
                - GET
                - OPTIONS
      routes:
        - id: availability-service
          uri: lb://availability-service
          predicates:
            - Path=/api/v1/availability/{id}
            - Method=GET
          filters:
            - AuthenticateFilter
            - name: AuthorizeFilter
              args:
                configValue: PATIENT

        - id: availability-service
          uri: lb://availability-service
          predicates:
            - Path=/api/v1/availability/info/{id}
            - Method=GET
          filters:
            - AuthenticateFilter
            - name: AuthorizeFilter
              args:
                configValue: PATIENT

        - id: availability-service
          uri: lb://availability-service
          predicates:
            - Path=/api/v1/availability/{id}
            - Method=DELETE
          filters:
            - AuthenticateFilter
            - name: AuthorizeFilter
              args:
                configValue: DOCTOR

        - id: availability-service
          uri: lb://availability-service
          predicates:
            - Path=/api/v1/availability/{id}
            - Method=POST
          filters:
            - AuthenticateFilter
            - name: AuthorizeFilter
              args:
                configValue: DOCTOR

        - id: appointment-service
          uri: lb://appointment-service
          predicates:
            - Path=/api/v1/appointment/
            - Method=POST
          filters:
            - AuthenticateFilter
            - name: AuthorizeFilter
              args:
                configValue: PATIENT

        - id: appointment-service
          uri: lb://appointment-service
          predicates:
            - Path=/api/v1/appointment/{id}
            - Method=DELETE
          filters:
            - AuthenticateFilter

        - id: appointment-service
          uri: lb://appointment-service
          predicates:
            - Path=/api/v1/appointment/user/{id}
            - Method=GET
          filters:
            - AuthenticateFilter
            - name: AuthorizeFilter
              args:
                configValue: PATIENT

        - id: appointment-service
          uri: lb://appointment-service
          predicates:
            - Path=/api/v1/appointment/doctor/{id}
            - Method=GET
          filters:
            - AuthenticateFilter
            - name: AuthorizeFilter
              args:
                configValue: DOCTOR

        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/auth/**

        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/user/
            - Method=GET
          filters:
            - AuthenticateFilter

        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/user/userId
            - Method=GET
          filters:
            - AuthenticateFilter

        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/user/userInfo/{id}
            - Method=GET
          filters:
            - AuthenticateFilter

        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/user/doctors/
            - Method=GET
          filters:
            - AuthenticateFilter
            - name: AuthorizeFilter
              args:
                configValue: PATIENT

      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin, RETAIN_FIRST


server:
  port: 8087

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
